-- MySQL Script generated by MySQL Workbench
-- Qui 20 Out 2016 00:08:02 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema databaseprfight
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema databaseprfight
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `databaseprfight` DEFAULT CHARACTER SET utf8 ;
USE `databaseprfight` ;

-- -----------------------------------------------------
-- Table `databaseprfight`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databaseprfight`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databaseprfight`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databaseprfight`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `faixa` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(125) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `salt` VARCHAR(125) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 1,
  `descricao` VARCHAR(500) NULL,
  `roles_id` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `alunos_role_id_idx` (`roles_id` ASC),
  CONSTRAINT `users_roles_id`
    FOREIGN KEY (`roles_id`)
    REFERENCES `databaseprfight`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databaseprfight`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databaseprfight`.`login_attempts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `created_alt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk_login_attempts_id_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_login_attempts_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `databaseprfight`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `databaseprfight`.`recoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databaseprfight`.`recoveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `passwords_id_user_idx` (`id_user` ASC),
  CONSTRAINT `recoveries_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `databaseprfight`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
