 <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-body">
                    
                        <form class="form-horizontal" action="<?php echo BASE; ?>recuperar/solicitar/" 
                        method="post" >
                            <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                          <div class="form-group">
                            <label for="email" class="col-sm-3 control-label">E-mail:</label>
                            <div class="col-sm-8">
                              <input type="text" class="form-control" name="email" id="email" placeholder="exemplo@exemplo.com" value="<?php echo $this->request->post('email')?>">
                            </div>
                          </div>

                          <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                              <button type="submit" class="btn btn-success">Solicitar</button>
                            </div>
                          </div>
                        </form
                       
                </div>
            </div>
        </div>
    </div>
