 <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-body">
                    
                        <form class="form-horizontal" action="<?php echo BASE; ?>recuperar/alterarSenha/<?php echo $view_token; ?>" 
                        method="post" >
                            <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                          <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">Nova Senha:</label>
                            <div class="col-sm-8">
                              <input type="password" class="form-control" name="password" id="password" placeholder="sua sennha">
                            </div>
                          </div>

                          <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                              <button type="submit" class="btn btn-success">Alterar Senha</button>
                            </div>
                          </div>
                        </form
                       
                </div>
            </div>
        </div>
    </div>
