<div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
				<div class="panel-body">
					<table class="table table-bordered">

						<thead>
							<tr>
								<th>Nome</th>
								<th>Faixa</th>
								<th>foto</th>
								<th>descrição</th>
							</tr>
						</thead>

						<tbody>	

						<?php if ($view_users): 

								foreach ($view_users as $user) : 
						?>	
								<?php if ($user->status==1): ?>
								<tr>
								<td><?php echo $user->name; ?></td>
								<td><?php echo $user->faixa; ?></td>
								<td>
								<figure class="foto-perfil">
								<a class="example-image-link" href="../public/uploads/users/<?php echo $user->name; ?>/<?php echo $user->image; ?>" data-lightbox="example-1"  data-lightbox="example-set" data-title="<?php echo $user->name; echo " "; echo $user->faixa;?>">
          
                    			   <img class="example-image" src="../public/uploads/users/<?php echo $user->name; ?>/<?php echo $user->image; ?>"/>									
								</figure>
                    			</td>
                    			<td><?php echo $user->descricao; ?></td>
												
								</tr>
								<?php endif; ?>
								
						<?php
								endforeach;
							 endif; 

							 ?>
						</tbody>

					</table>

				</div>
			</div>
		</div>
</div>