<div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" href="#collapse1"> Kata </a>
           </h4>
             </div>
                <div id="collapse1" class="panel-collapse collapse ">
                
                    <div class="panel-group" id="accordion2">             
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                           <a data-toggle="collapse" data-parent="#accordion2"  href="#collapse2">Heian Shodan - Faixa Branca</a>
                             </h4>
                          </div>
                        <div id="collapse2" class="panel-collapse collapse">
                     <figure class="foto-perfil">
                   <a class="example-image-link" href="../_imagens/HeianShodan.jpg" data-lightbox="exemple-1" data-title="Heian Shodan - Kata Faixa Branca">
                <img class="example-image" src="../_imagens/HeianShodan.jpg" alt="heian nidan" />
               </a>
             </figure> 
            </div>
         </div> 

                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <a data-toggle="collapse" data-parent="#accordion2" href="#collapse3">Heian Nidan - Faixa Amarela</a>
                        </h4>
                          </div>
                            <div id="collapse3" class="panel-collapse collapse">
                              <figure class="foto-perfil">
                                <a class="example-image-link " href="../_imagens/HeianNidan.jpg" data-lightbox="exemple-1"   data-title="Heian Nidan - Kata Faixa Amarela">
                                <img class="example-image" src="../_imagens/HeianNidan.jpg" alt="heian nidan" />
                            </a>
                       </figure> 
                    </div>
                 </div>
       
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion2"  href="#collapse4">Heian Sandan - Faixa Vermelha</a>
                      </h4>
                        </div>
                          <div id="collapse4" class="panel-collapse collapse">
                            <figure class="foto-perfil">
                              <a class="example-image-link " href="../_imagens/HeianSandan.jpg" data-lightbox="exemple-1"   data-title="Heian Sandan - Kata Faixa Vermelha">
                            <img class="example-image" src="../_imagens/HeianSandan.jpg" alt="Heian Sandan" />
                          </a>
                        </figure> 
                     </div>
                  </div>    
            
             
               <div class="panel panel-default">
                 <div class="panel-heading">
                   <h4 class="panel-title">
                     <a data-toggle="collapse" data-parent="#accordion2" href="#collapse5">Heian Yodan - Faixa Laranja</a>
                       </h4>
                         </div>
                           <div id="collapse5" class="panel-collapse collapse">
                             <figure class="foto-perfil">
                               <a class="example-image-link " href="../_imagens/HeianYondan.jpg" data-lightbox="exemple-1"  data-title="Heian Yodan - Kata Faixa Laranja">
                             <img class="example-image" src="../_imagens/HeianYondan.jpg" alt="Heian Yondan" />
                           </a>
                         </figure>
                       </div>
                    </div>
                
          
                   <div class="panel panel-default">
                     <div class="panel-heading">
                       <h4 class="panel-title">
                         <a data-toggle="collapse" data-parent="#accordion2" href="#collapse6">Heian Godan - Faixa Verde</a>
                           </h4>
                             </div>
                               <div id="collapse6" class="panel-collapse collapse">
                                 <figure class="foto-perfil">
                                   <a class="example-image-link " href="../_imagens/HeianGodan.jpg" data-lightbox="exemple-1"  data-title="Heian Godan - Kata Faixa Verde">
                                 <img class="example-image" src="../_imagens/HeianGodan.jpg" alt="Heian Godan" />
                               </a>
                             </figure>
                           </div>
                        </div>


                    <div class="panel panel-default">
                      <div class="panel-heading">
                         <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion2" href="#collapse7">Tekki Shodan - Faixa Roxa</a>
                           </h4>
                             </div>
                               <div id="collapse7" class="panel-collapse collapse">
                                  <figure class="foto-perfil">
                                     <a class="example-image-link " href="../_imagens/TekkiShodan.jpg" data-lightbox="exemple-1"  data-title=" Tekki Shodan - Kata Faixa Roxa">
                                 <img class="example-image" src="../_imagens/TekkiShodan.jpg" alt="Tekki Shodan" />
                               </a>
                             </figure>
                           </div>
                        </div>
  
                    <div class="panel panel-default">
                      <div class="panel-heading">
                         <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion2" href="#collapse8">Tekki Nidan - Faixa Roxa</a>
                           </h4>
                             </div>
                               <div id="collapse8" class="panel-collapse collapse">
                                  <figure class="foto-perfil">
                                     <a class="example-image-link " href="../_imagens/tekkinidan.jpg" data-lightbox="exemple-1"  data-title=" Tekki Nidan - Kata Faixa Roxa">
                                 <img class="example-image" src="../_imagens/tekkinidan.jpg" alt="Tekki Nidan" />
                               </a>
                             </figure>
                           </div>
                        </div>

                    <div class="panel panel-default">
                      <div class="panel-heading">
                         <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion2" href="#collapse9">Tekki Sandan - Faixa Roxa</a>
                           </h4>
                             </div>
                               <div id="collapse9" class="panel-collapse collapse">
                                  <figure class="foto-perfil">
                                     <a class="example-image-link " href="../_imagens/tekkisandan.gif" data-lightbox="exemple-1" data-title="Tekki Sandan - Kata Faixa Roxa">
                                 <img class="example-image" src="../_imagens/tekkisandan.gif" alt="Tekki Sandan" />
                               </a>
                             </figure>
                           </div>
                        </div>

                    <div class="panel panel-default">
                      <div class="panel-heading">
                         <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion2" href="#collapse10">Bassai Dai - Faixa Marrom</a>
                           </h4>
                             </div>
                               <div id="collapse10" class="panel-collapse collapse">
                                  <figure class="foto-perfil">
                                    <a class="example-image-link" href="../_imagens/BassaiDai.jpg" data-lightbox="exemple-1" data-title="Bassai Dai - Kata Faixa Marrom">
                                 <img class="example-image" src="../_imagens/BassaiDai.jpg" alt="Tekki Sandan" />
                               </a>
                             </figure>
                           </div>
                        </div>

                     <div class="panel panel-default">
                       <div class="panel-heading">
                         <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion2" href="#collapse11">Jion - Faixa Preta</a>
                           </h4>
                             </div>
                               <div id="collapse11" class="panel-collapse collapse">
                                  <figure class="foto-perfil">
                                     <a class="example-image-link " href="../_imagens/jion.gif" data-lightbox="exemple-1"  data-title="Jion- Kata Faixa Preta">
                                 <img class="example-image" src="../_imagens/jion.gif" alt="Jion" />
                               </a>
                             </figure>
                           </div>
                        </div>

                        <div class="panel panel-default">
                          <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse12">Enpi - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse12" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title=" Enpi - Kata Faixa Preta" href="../_imagens/empi.gif">
                                        <img class="exemple-image" src="../_imagens/empi.gif"  alt="Enpi">
                                     </a>
                                   </figure>
                                 </div>
                              </div>

                        <div class="panel panel-default">
                          <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse13">Jitte - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse13" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Jitte - Kata Faixa Preta" href="../_imagens/jitte.gif">
                                        <img src="../_imagens/jitte.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>

                        <div class="panel panel-default">
                          <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse14">Hangetsu - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse14" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Hangetsu - Kata Faixa Preta" href="../_imagens/hangetsu.gif">
                                        <img src="../_imagens/hangetsu.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>

                        <div class="panel panel-default">
                          <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse16">Kanku dai - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse16" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Kanku dai - Kata Faixa Preta" href="../_imagens/kankudai.gif">
                                        <img src="../_imagens/kankudai.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>

                         <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse17">Gankaku - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse17" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Gankaku - Kata Faixa Preta" href="../_imagens/gangaku.gif">
                                        <img src="../_imagens/gangaku.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>

                         <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse18">Nijushiho - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse18" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Nijushiho - Kata Faixa Preta" href="../_imagens/nijushijo.gif">
                                        <img src="../_imagens/nijushijo.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div> 

                         <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse19">Jiin - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse19" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Jiin - Kata Faixa Preta" href="../_imagens/jiin.gif">
                                        <img src="../_imagens/jiin.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>

                        <div class="panel panel-default">
                          <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse20">Bassai sho - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse20" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Bassai sho - Kata Faixa Preta" href="../_imagens/bassai_sho.gif">
                                        <img src="../_imagens/bassai_sho.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div> 

                         <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse21">Kanku sho - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse21" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Kanku sho - Kata Faixa Preta" href="../_imagens/kankusho.gif">
                                        <img src="../_imagens/kankusho.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div> 

                         <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse22">Chinte - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse22" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Chinte - Kata Faixa Preta" href="../_imagens/chinte.gif">
                                        <img src="../_imagens/chinte.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div> 

                        <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse23">Wankan - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse23" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Chinte - Kata Faixa Preta" href="../_imagens/wankan.gif">
                                        <img src="../_imagens/wankan.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>


                        <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse24">Sochin - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse24" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Sochin - Kata Faixa Preta" href="../_imagens/sochin.gif">
                                        <img src="../_imagens/sochin.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>


                        <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse25">Meikyo - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse25" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Meikyo - Kata Faixa Preta" href="../_imagens/meikyo.gif">
                                        <img src="../_imagens/meikyo.gif" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>                      
                          
                        <div class="panel panel-default">
                           <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse26">Gojushiho sho - Faixa Preta</a>
                                 </h4>
                                   </div>
                                     <div id="collapse26" class="panel-collapse collapse">
                                       <figure class="foto-perfil">
                                          <a class="exemple-image-link" data-lightbox="exemple-1" data-title="Sochin - Kata Faixa Preta" href="../_imagens/gojushihosho.jpg">
                                        <img src="../_imagens/gojushihosho.jpg" class="exemple-image">
                                     </a>
                                   </figure>
                                 </div>
                              </div>
        



                     </div>    
                  </div>
                </div>


      </div>
