<table id="eventos">
            <caption>Eventos de 2016</caption>

            <tr>  <td class="ce"> XX/XX/XX </td> <td class="cd"> .... </td>  </tr>
            <tr>  <td class="ce"> XX/XX/XX </td> <td class="cd"> .... </td>  </tr>

        </table>

        <table id="aulas">
            <caption>Aulas do Ano</caption>

            <tr>  <td rowspan="4" class="ce"> Janeiro </td> <td class="cd"> .... </td>  </tr>
            <tr>                                             <td class="cd"> .... </td>   </tr>
            <tr>                                             <td class="cd"> .... </td>   </tr>
            <tr>                                             <td class="cd"> .... </td>   </tr>
            <tr>  <td rowspan="4" class="ce"> Fevereiro </td> <td class="cd"> .... </td>  </tr>
            <tr>                                             <td class="cd"> .... </td>   </tr>
            <tr>                                             <td class="cd"> .... </td>   </tr>
            <tr>                                             <td class="cd"> .... </td>   </tr>


        </table>

            