<section id="fotos">
                <figure class="foto-perfil">
                    
                   <a class="example-image-link" href="../_imagens/perfil.jpg" data-lightbox="example-1"  data-lightbox="example-set" data-title="Paulo Ribeiro Faixa Preta 5º Dan">
          
                       <img class="example-image" src="../_imagens/perfil.jpg" alt="imagem de perfil do professor" />
          
                    </a>
                </figure>
                   
            </section>
            