 <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                        <form class="form-horizontal" action="<?php echo BASE; ?>login/logar/" 
                        method="post">                     
                          <div class="form-group">
                            <label for="username" class="col-sm-3 control-label">Nome de Usuario:</label>
                            <div class="col-sm-8">
                              <input type="text" value="<?php echo $this->request->post('username')?>" class="form-control" name="username" id="username" placeholder="exemplo">
                            </div>
                          </div>

                          <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">Senha:</label>
                            <div class="col-sm-8">
                              <input type="password" class="form-control" name="password" id="password" placeholder="senha">
                            </div>
                          </div>
                         
                          <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                              <button type="submit" class="btn btn-success">Entrar</button>
                            </div>
                          </div><footer id="rodape">
                            
                         
                           <a href="<?php echo BASE . 'cadastro/'; ?>"><p>Ainda Não é cadastrado?</p></a>
                           <a href="<?php echo BASE . 'recuperar/'; ?>"><p>Esqueceu sua senha?</p>></a>
                            </footer>
                        </form>

                       
                </div>
            </div>
        </div>
    </div>
