<footer id="rodape">
                <p>
                    Rua: 87 Nº71, Bairro Cajupiranga - Parnamirim/RN  &nbsp; &nbsp; Telefone:(84) 99408-0098
                </p>
                                
                   <p>
                    
                    Copyright &copy; 2016 - by Ewertton Elias <br />
                    
                </p>
 </footer>
           
           </div>
   <script src="<?php echo JS; ?>lightbox-plus-jquery.min.js"></script>
    

    </body>
</html>

