<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Ewertton Klaytton">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $view_title; ?></title>
  <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css"> 
  <link rel="stylesheet" href="<?php echo CSS; ?>professor.css" type="text/css"> 
  <link rel="stylesheet"   href="<?php echo BOWER; ?>/bootstrap/dist/css/bootstrap.css" type="text/css"> 
  <link rel="stylesheet" href="<?php echo CSS; ?>estilo.css" type="text/css" />
  <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">      
     
     <script src="<?php echo JS; ?>jquery.min.js"></script>
    <script src="<?php echo JS; ?>bootstrap.min.js"></script>
    <script src="<?php echo JS; ?>jquery.min.js"></script>
	<?php 
		echo $add_css;
		echo $add_js;
	?>
</head>
<body>
<div id="interface">

	<header id="cabecalho">
          <nav role="navigation" class="navbar  navbar-default"> 
        
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class=" navbar-toggle">
                    <span class="sr-only"> navegação responsiva</span>
                    <span class="icon-bar"> </span>
                    <span class="icon-bar"> </span>
                    <span class="icon-bar"> </span>
                </button>
                <a href="#" class="navbar-brand">Menu</a>
            </div>
            
           <div id="navbarCollapse" class="collapse navbar-collapse">
           
               <ul class="nav navbar-nav">
                   
                   <li> <a href="<?php echo BASE . 'index/index'; ?>">Home</a> </li>
                    <li> <a href="<?php echo BASE . 'index/escola'; ?>"> Escola</a> </li>
                    <li> <a href="<?php echo BASE . 'index/professores'; ?>" > Professores</a> </li>
                    <li> <a href="<?php echo BASE . 'index/alunos'; ?>">Alunos</a> </li>
                    <li> <a href="<?php echo BASE . 'index/fotos'; ?>">Fotos </a></li>
                    <li> <a href="<?php echo BASE . 'index/eventos'; ?>">Eventos</a> </li>
                    <li> <a href="<?php echo BASE . 'index/aprendendoMais'; ?>" >Aprendendo Mais </a></li>
                    <li> <a href="<?php echo BASE . 'login/'; ?>">Login</a></li></li>
                   
               </ul>
           </div>
            
        </nav>
            <hgroup>
                <h1> Escola de Karatê Shotokan PR Fight - Parnamirim/RN</h1>
                <h2>Shihan: Paulo Ribeiro Faixa Preta 5º Dan</h2>
            </hgroup>
           
        </header>

